In [1]:
import pandas as pd 
import numpy as np
from dotenv import load_dotenv 
import matplotlib.pyplot as plt 
import seaborn as sns 
from pandas import json_normalize
import requests
import os
import datetime
import json

In [2]:
datetime.datetime.now().date

In [3]:
load_dotenv()

True

In [4]:
marketaux_key = os.getenv("fin_news")

In [5]:
marketaux_key

'0Hd61QoCbdZsTArWidBYtdyBrLizlq3GTz7RZffm'

In [25]:
request = requests.get(f"https://api.marketaux.com/v1/news/all?symbols=VFS&language=en&api_token={marketaux_key}&filter_entities=true") 
print (request.status_code)

200

In [26]:
request.text

'{"meta":{"found":0,"returned":0,"limit":3,"page":1},"data":[]}'

In [27]:
df = json_normalize(request.json()['data'])

In [28]:
df

Empty DataFrame
Columns: []
Index: []

In [36]:
news_api_key = os.getenv("news_api_key")

In [37]:
request = requests.get(f"https://newsapi.org/v2/everything?q=vinfast&apiKey={news_api_key}&language=en")

In [38]:
# I will need to translate the text
df = json_normalize(request.json()['articles'])

In [39]:
df.head()

,author,title,description,url,urlToImage,publishedAt,content,source.id,source.name
0,Abdul Rahman,VinFast Auto Ltd. (VFS) A Top Mid-Cap Stock to...,VinFast Auto Ltd (NASDAQ:VFS) is one of the to...,https://finance.yahoo.com/markets/stocks/artic...,https://s.yimg.com/lo/mysterio/api/BE90DD632B4...,2026-07-07T22:39:23Z,VinFast Auto Ltd (NASDAQ:VFS) is one of the to...,None,Yahoo Entertainment
1,Talha Qureshi,VinFast Auto (VFS) Among Our Penny Stocks That...,VinFast Auto Ltd. (NASDAQ:VFS) is one of the B...,https://finance.yahoo.com/markets/stocks/artic...,https://s.yimg.com/lo/mysterio/api/D3BCB7D1FEA...,2026-06-16T18:46:37Z,VinFast Auto Ltd. (NASDAQ:VFS) is one of the B...,None,Yahoo Entertainment
2,GlobalData,VinFast’s domestic sales surge 58% in June,Vietnamese automaker launches new entry-level ...,https://www.just-auto.com/news/vinfasts-domest...,https://s.yimg.com/lo/mysterio/api/61D6A35819C...,2026-07-13T09:24:11Z,Vietnamese battery electric vehicle (BEV) manu...,None,Just-auto.com
3,Nicholas Gordon,Vietnam’s economy is one of the fastest-growin...,Hanoi wants to grow the economy by 10% annuall...,https://finance.yahoo.com/economy/articles/vie...,https://s.yimg.com/lo/mysterio/api/523208517B1...,2026-06-16T07:00:00Z,Can Vietnam copy China's playbook? It has a st...,None,Yahoo Entertainment
4,Gerard Lye,VinFast VF2 launched in Vietnam – budget city ...,Vietnamese automaker VinFast has unveiled the ...,https://paultan.org/2026/07/08/vinfast-vf2-lau...,https://paultan.org/image/2026/07/VinFast-VF2-...,2026-07-08T02:24:14Z,Vietnamese automaker VinFast has unveiled the ...,None,Paul Tan's Automotive News

In [40]:
df.content.iloc[0]

'VinFast Auto Ltd (NASDAQ:VFS) is one of the top mid-cap stocks to own for the long term, according to hedge funds. On June 18, VinFast Auto Ltd (NASDAQ:VFS) confirmed the availability of its VF 8 ele… [+1707 chars]'

In [85]:
# Translating the text using google translate
df.isna().sum()

author         18
title           0
description     4
url             0
urlToImage      9
publishedAt     0
content         0
source.id      41
source.name     0
dtype: int64

In [67]:
df.head()

,author,title,description,url,urlToImage,publishedAt,content,source.id,source.name,description_translated
0,Raphaëlle Baut,Vinfast se sépare de ses usines (et des lourde...,Pour masquer ses pertes colossales et faire le...,https://www.numerama.com/vroom/2257897-vinfast...,https://c0.lestechnophiles.com/www.numerama.co...,2026-05-21T12:43:58Z,Pour masquer ses pertes colossales et faire le...,None,Numerama,<coroutine object Translator.translate at 0x15...
1,"no-reply@tinhte.vn (thanhtung6868), thanhtung6868",VinFast sẽ ra mắt sản phẩm mới vào 20/05/2026 ...,VinFast sẽ ra mắt sản phẩm mới vào 20/05/2026 ...,https://tinhte.vn/thread/vinfast-se-ra-mat-san...,https://photo2.tinhte.vn/data/attachment-files...,2026-05-15T16:47:32Z,VinFast s ra mt sn phm mi vào 20/05/2026 ti ây...,None,Tinhte.vn,<coroutine object Translator.translate at 0x16...
2,None,Vietnam-Philippines partnership puts VinFast i...,None,https://consent.yahoo.com/v2/collectConsent?se...,None,2026-06-08T17:50:42Z,"If you click 'Accept all', we and our partners...",None,Yahoo Entertainment,<coroutine object Translator.translate at 0x16...
3,Chen Kobe,三年前補助 VinFast 電動車建廠，現在卻對簿公堂,政府重金補貼吸引車廠進駐，沒想到換來一場空，雙方只好走進法院撕破臉，這場荒唐劇情現在正上演。...,https://technews.tw/2026/05/22/north-carolina-...,https://img.technews.tw/wp-content/uploads/202...,2026-05-22T02:00:35Z,VinFast VinFast Jeff Jackson Josh Stein Chatha...,None,Technews.tw,<coroutine object Translator.translate at 0x16...
4,"no-reply@tinhte.vn (thanhtung6868), thanhtung6868","VinFast, NVIDIA và Autobrains Hợp Tác Phát Tri...","Hợp tác chiến lược giữa VinFast, NVIDIA và Aut...",https://tinhte.vn/thread/vinfast-nvidia-va-aut...,https://photo2.tinhte.vn/data/attachment-files...,2026-06-05T13:22:23Z,"Hp tác chin lc gia VinFast, NVIDIA và Autobrai...",None,Tinhte.vn,<coroutine object Translator.translate at 0x16...

# Historical stock data

In [17]:
#This shows stock data
eod_key = os.getenv("fin_historical_data")

In [80]:
request = requests.get(f"https://eodhd.com/api/eod/MCD.US?api_token={eod_key}&fmt=json")

In [81]:
request.status_code

200

In [84]:
json_normalize(request.json())

           date    open    high     low   close  adjusted_close   volume
0    2025-06-16  303.14  304.00  295.75  296.29        289.2828  4045700
1    2025-06-17  296.00  296.01  291.79  292.31        285.3969  3379000
2    2025-06-18  293.00  293.11  288.60  289.63        282.7803  4008700
3    2025-06-20  289.77  290.61  285.57  287.46        280.6616  7085000
4    2025-06-23  288.52  289.52  285.87  289.52        282.6729  5172500
..          ...     ...     ...     ...     ...             ...      ...
246  2026-06-09  277.61  285.31  276.04  282.25        282.2500  5431700
247  2026-06-10  284.32  286.45  282.30  282.52        282.5200  4152700
248  2026-06-11  282.84  286.25  281.04  284.77        284.7700  4565400
249  2026-06-12  286.00  287.66  284.03  284.81        284.8100  4026900
250  2026-06-15  284.23  288.22  283.61  286.12        286.1200  4279952

[251 rows x 7 columns]